### ISSUE TITLE
How to solve this permission issue? 

### ISSUE THREAD

**Issue by Alafun** [touhid314/Coursera-Downloader#1] opened 2023-09-22 08:31 UTC
![image](https://github.com/touhid314/Coursera-Downloader/assets/78416589/3f805cfc-8933-413b-b652-6a5809c1d9e1)

> Permission denied: 

Windows 11 
![image](https://github.com/touhid314/Coursera-Downloader/assets/78416589/c76995cd-1667-4a88-87f3-b93dbed9f633)

**Comment by touhid314** [comment] 2023-09-22 08:49
This is due to a recent update of chrome. And apparently now also for edge. The issue is still unsolved for the browser cookie 3 module which is causing the problem (https://github.com/borisbabic/browser_cookie3/issues/180). 

As of now, the work around is that, logout of Coursera.org in chrome and edge. Then login to Coursera.org in any other browser (eg. Firefox, opera etc.). Make sure that chrome and edge are closed and not just minimized. It should work.

Alternatively, you can rollback to an earlier version of chrome as indicated on the browser cookie 3 issue thread.

**Comment by Alafun** [comment] 2023-09-22 08:58
I see, I will try and share my feedback.

**Comment by Alafun** [comment] 2023-09-24 04:19
Unable to solve.

**Comment by touhid314** [comment] 2023-09-24 06:04
logout of Coursera.org in Chrome and Edge. Then log in to Coursera.org in any other browser (eg. Firefox). Make sure that Chrome and Edge are closed and not just minimized. **As Edge always keeps on running in the background, you have to close it on the task manager. Go to Task Manager> Processes > Background Processes, select "Microsoft Edge" and click End Task.**

Sorry for the inconvenience. I am working to solve the issue on the code.

**Comment by AmanyATA** [comment] 2023-10-22 12:46
after trying this solution and click download it close suddenly without any change

**Closed** 2023-12-03 05:00 UTC

**Comment by touhid314** [comment] 2023-12-03 05:02
The issue has been solved now. Cookies can be fetched from Chrome. Only Chrome and Firefox can be used for authentication now. Other browsers cannot be used.
